[package]
name = "toml_problem"
version = "0.1.0"
authors = ["Craig Gallagher <github.cg@cgtracker.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
